### ISSUE TITLE
Request: Could you give the option to See file name

### ISSUE THREAD

**Issue by gpryce-medullan** [ericcornelissen/pinned-tabs-for-atom#2]
Hello, 

First of all, thank you for writing this plugin (and your fast response to my last issue). I was wondering if you could put in a feature that would allow me to see the file name of the pinned files. To me, pinned files means that they are the most important file to me now, so would even what to see there full names regardless of how many other files I have opened, so I don't lose track of multiple pinned files.

**Comment by ericcornelissen** [comment]
Hey,

Thank you, I'm glad you like it! Could you elaborate a bit on how you would like to see this implemented, because I'm not quite sure what you mean...

**Comment by gpryce-medullan** [comment]
Okay, 

So when you pin a tab now, you see a dot. Instead of the dot, I would like the options to show the file name (and possibly an icon, like the dot). I would also be nice to ensure,  if possible, that it pinned tabs are always first in the tab list.

**Comment by ericcornelissen** [comment]
I'm still not quite sure what you mean :sweat_smile: One of the main points, for me at least, of pinned tabs is that they are very small and only display an icon. So I do not really understand why (and how) you would want to see the file name...

I'm however busy with making it so that pinned tabs are always first in the list, but I've not yet figured out how to do this properly :pensive:

**Comment by gpryce-medullan** [comment]
(Sorry for the delay, though I had replied) Okay. In visual studio pinned tabs are tabs that you put priority on no matter what other tabs you are working on. So if you are working on the orders functionality, you would want the ordersController, ordersView, etc. You might opening the app.js file or so, but you want to priorities the order files. That is what you are doing with pinned tabs now thou, but it just that I wouldn't necessarily want a pinned tab to be represented by a dot.

**Comment by Gunny123** [comment]
Pinned tabs now have icons.

**Comment by ericcornelissen** [comment]
Indeed, as Gunny123 said, pinned tabs have icons based on their file type since a few version. Besides that, regarding the order of the tabs, I pushed a commit to Github yesterday (so I didn't publish it to APM yet) which ensures that when opening a new tab, it is opened after all the tabs that are pinned.

I hope all this solved your problem. If not, just let me know!

**Comment by ericcornelissen** [comment]
I assume this issue can be closed, since (from my point of view) the issue is resolved. And the creator of the issue hasn't replayed for quite some time.
