### ISSUE TITLE
Wrong tabs pinned on reopening Atom if "Project Find Results" tab was pinned

### ISSUE THREAD

**Issue by OmeGak** [ericcornelissen/pinned-tabs-for-atom#21]
I noticed that when I start Atom I always had a tab I hadn't pinned among the pinned ones. I found out that this is caused by *Project Find Results* tab, which I usually keep pinned, not existing when I launch start. It seems the package tries to keep the same amount of tabs pinned as I had before quitting, but now one of them doesn't exist and it assumes the leftmost non-pinned tab it's the one that was.

To reproduce the issue:
* Have at least one buffer tab open.
* Do a "Find in Project".
* Pin "Project Find Results" tab.
* Restart Atom

**Comment by ericcornelissen** [comment]
Thx for reporting this. I was aware this could happen, but never encountered a situation where it would, which is why I sticked with this approach...

But now that you found a way to break my approach I had to change how the package works (something I should've done earlier probably, considering I was aware of the risks :sweat_smile:) I found another way to remember what tabs where pinned the last time the editor was open, but I'm not 100% sure it will always work... So I pushed the branch with that solution to Github and will be testing it thoroughly in the next few days. You can help me testing by cloning the repo into `..\.atom\packages\` and checking out on branch `issue-21` :smile:

**Comment by ericcornelissen** [comment]
I can't seem to find any problems with the new approach so I'm just going to close this issue. The fix will be included in the next update (which I will get out asap) :smile:

**Comment by ericcornelissen** [comment]
No problem, thanks for letting me know so quickly :smile: I'll look into this asap!

**Comment by ericcornelissen** [comment]
You where almost right. `pdf-view` doesn't change the ID, it actually doesn't have an ID (as it is a jQuery object for some reason :sweat:). A similar problem most likely occurs with some other package out there. Besides that the image viewer build into Atom also doesn't give an ID.

So, I came up with a different solution :smile: the package will now use an items URI if it cannot find an ID (using the URI can lead to different problems, because it is just a string of the file path... But its the best I could come up with))
