### ISSUE TITLE
Keep tabs pinned when switching projects

### ISSUE THREAD

**Issue by onetrev** [ericcornelissen/pinned-tabs-for-atom#25]
Is it possible to maintained the pinned state when switching projects? Would be great if so! Atom Project Manager, which is really popular, has recently added the ability to properly switch projects in the same Atom window (huge time saver!), but when you do this your pinned tabs are lost. Thanks!

**Comment by ericcornelissen** [comment]
Unfortunately this is not easy to do, and should probably an issue at the [Atom Project Manager](https://atom.io/packages/project-manager) package itself. This is because this package cannot know that a new project has been loaded with the Atom Project Manager, nor can it assume that the user uses the Atom Project manager package.

However, I do think it will be possible for the Atom Project Manager to make this possible in one way or another. 🙂
