### ISSUE TITLE
Match file icons with the well known package "File-icons

### ISSUE THREAD

**Issue by Gunny123** [ericcornelissen/pinned-tabs-for-atom#3]
Would there be a way to mach the icons with the user's file icons already installed for uniformity? I use <a href="https://github.com/DanBrooker/file-icons" target="_blank">Dan Brooker's</a> file icons in Atom currently. It would be nice to use those icons when pinning. 

Great little package so far it's great when referencing core files.

**Comment by ericcornelissen** [comment]
I have been look at this, but unfortunately I cannot think of a way to use the file-icons package the user is using because of the fact that different packages implement this in different ways :pensive: Fortunately for you, I've been working on implementing Dan Brookers file icons because it is much more popular then the package I used in the last version. I hope I can publish this version later today!

**Comment by Gunny123** [comment]
Let me know if you want some help.

**Comment by ericcornelissen** [comment]
Thank you for the offer but I was already done :+1: But, feel free to do a pull request if you think there is something that can be improved upon!
