### ISSUE TITLE
Keep filenames visible

### ISSUE THREAD

**Issue by taradinoc** [ericcornelissen/pinned-tabs-for-atom#35]
It'd be nice to have the option to keep the filenames visible on pinned tabs instead of collapsing them, for when I'm working on more than one file of the same type.

This would be similar to the way Visual Studio's pinned tabs work: there's a visual indicator that they're pinned, but otherwise they look like normal tabs.

**Comment by ericcornelissen** [comment]
Thank you for requesting the enhancement, but sorry for the delay in my response (been on holiday 😅)

I like your suggestion, So I decided to start working on it. You can find the changes so far on the [visual-studio-pinning](https://github.com/ericcornelissen/pinned-tabs-for-atom/tree/visual-studio-pinning) branch. It is already functional, so I would like to ask you if you could try it out 😄 I'm not quite sure about the styling yet though... For example in the [Atom-dark](https://atom.io/themes/atom-dark-ui) theme it currently looks like this:

![capture](https://user-images.githubusercontent.com/3742559/28747970-d84390fe-74ab-11e7-80d5-4371c87c2f0c.jpg)

Where, as you suggested, there is (always) a visual indication the tab is pinned. But in e.g. [One-dark](https://atom.io/themes/one-dark-atom) you need to hover over the tab to see if its pinned, see:

![capture](https://user-images.githubusercontent.com/3742559/28747978-0571aa3e-74ac-11e7-89b0-30a192252057.jpg)

Do you think the pinned icon should always be shown? I'm doubting this since one might have chosen that theme partly because it hides these icons...

**Comment by ericcornelissen** [comment]
After using the Visual Studio style pinned tabs for a few days with a theme that hides the indicating, I think it is safe to say that it should be displayed, so I updated that in 7f79d33.

@taradinoc, what do you think about the functionality right now?

**Comment by aioue** [comment]
Seeing the file name, and a permanent indicator of the pin status is great. The indicator looks good.

I've also seen subtle highlighting if you are looking for options:

![image](https://user-images.githubusercontent.com/1254905/29355706-fa9b2cc2-8269-11e7-8cce-df2ac437d3bf.png)

Is this due for release?

**Comment by ericcornelissen** [comment]
@aioue, it is due for a release, I was more or less waiting for a response from @taradinoc... Anyway, I'll try to publish it in the upcoming days 😄 

> I've also seen subtle highlighting if you are looking for options:
[image]

You mean that tabs pinned in the Visual Studio way get a highlight while others don't (perhaps instead of the pin indicator)? I'm not sure... the main issue is that its hard to get that looking good on multiple themes. I might add it on popular demand, or you could write up a PR for it 👍

**Comment by ericcornelissen** [comment]
Closing this issue as the requested feature has been published with [v1.3.0](https://github.com/ericcornelissen/pinned-tabs-for-atom/releases/tag/v1.3.0) (see 4a56a82)
