### ISSUE TITLE
context menu for pinning "projects" and "git" tabs

### ISSUE THREAD

**Issue by mbroedl** [ericcornelissen/pinned-tabs-for-atom#50]
Not a highly important, but I thought I'd mention it:
I would like to pin things in my right dock (because there are too many tabs, and icons really are enough for that purpose), which works very well apart from the "projects" (which I moved there) and the "git" tab. Both pin well but only via the key combination or via the command directly, but the context menu does not show this option.
I have not figured out why, but after some restarts, these two tabs are not pinned any more. I suspect that they are somewhat different tabs, but I couldn't identify anything in the DOM that would reveal this difference. Maybe you have any thoughts on that? This might be related to #21?

As said, this is not hugely important, just a minor thought.
Many thanks for looking into this anyway. :)

**Comment by ericcornelissen** [comment]
The first problem has been resolved with commit c7560e1, after further investigation I've not been able to reproduce or identify a cause for the second problem. I will close this issue for now, if you find a reliable way to reproduce the second problem feel free to reopen this issue. I will publish the fix for the first problem before the end of the year 👍

**Comment by mbroedl** [comment]
Thanks a lot!
