### ISSUE TITLE
No modification icon

### ISSUE THREAD

**Issue by andrade** [ericcornelissen/pinned-tabs-for-atom#51]
I have the `file-icons` package installed with the option *Show icons in file tabs* disabled.

This appears to cause `pinned-tabs` (2.1.0 in Linux) to show no icon whatsoever in the pinned tabs. This wouldn't normally be a problem for me. However, it also doesn't inform the user when the tab has been modified.

In the following two images the first pinned tab has been modified. In the first image there is no indication that the file has been modified. In the second image I enabled *VS style pinning* with width 32 as a hack to receive modification feedback.

![screenshot from 2018-12-05 13-17-04](https://user-images.githubusercontent.com/4957940/49516108-af9bc300-f890-11e8-8439-a8b1fde468b3.png)

![screenshot from 2018-12-05 13-17-23](https://user-images.githubusercontent.com/4957940/49516112-b4607700-f890-11e8-946c-4f2100439d4d.png)

Ideally, we'd always get the blue circle informing us the file changed even with *VS style pinning* disabled.

This is related to Issue #32 but I'm not sure it is the same problem.

**Comment by ericcornelissen** [comment]
It seems this bug was caused by the fact that the `.icon` class on tabs stays present even if you disable the _Show icons in file tabs_ option (not sure if this was caused by file-icons or by Atom itself 🤔). The bug should be fixed with [v2.1.1](https://github.com/ericcornelissen/pinned-tabs-for-atom/releases/tag/v2.1.1), but there might be some file types for which the fix does not work.

Please update to the latest version and reopen if the issue persists 🙂
