### ISSUE TITLE
2.1.2 Icon Issue Persists

### ISSUE THREAD

**Issue by HintonR** [ericcornelissen/pinned-tabs-for-atom#54]
I'm not sure if you have any plans on further updates or adding features, but 2.1.2 has addressed the graphical issue with file-icons, however it has created (or did not address) other issues with other icons. 

So I was fiddling around with my Atom settings and decided to pin the settings tab to discover that a similar issue from before persists and now affect the icon for the settings tab. It's a very minor thing -- almost not worth patching.

But I had commented out this block:

/*.tab.pinned-tab > .title:not([class*="-icon"])::before {
  content: '\f011';
  display: inline-block;
  font-family: 'Octicons Regular';
  font-size: medium;
  font-style: normal !important;
  left: -76px;
  overflow: hidden;
  position: absolute;
  width: 0;
}*/

This resolves the issue. (this was also what I had commented out in the previous version for a quick fix) 

It makes sense to keep for users not adding icons to tabs, but it has been the culprit both times. I'm not sure how else to address it.

**Comment by ericcornelissen** [comment]
First of, just to be sure, #53 is no longer an issue, correct?


> I'm not sure if you have any plans on further updates or adding features

I might, there are some open issues for new features, why do you ask? Because the version number change was a patch? I guess because the change was really just a patch, I would say.


> however it has created (or did not address) other issues with other icons.

I am aware of some other tabs that don't show an icon/the incorrect icon when they're pinned (For example the tab for GitHub Pull Requests). I just haven't looked into fixing them as they seemed hard to fix and I didn't think they're that much of a problem. Mainly because these tabs (e.g. the Settings) won't usually be pinned.


> So I was fiddling around with my Atom settings and decided to pin the settings tab to discover that a similar issue from before persists and now affect the icon for the settings tab. It's a very minor thing -- almost not worth patching.

I just tested this and it is actually caused by the changes in 91a238cf1b666a4a204273f0811ba605bea07b5a for v2.1.2 :sweat_smile:

I was aware that this piece of CSS is the culprit of many problems, but never really figured out how to fix it. It is indeed there for people that are not using file-icons (at all or for tabs). But I think I did it now! See #55 for the fix. From initial testing this solves the current problem and does not bring back any previous issues I have had with this piece of code :tada: 

Thanks for bringing up these issues!

**Comment by ericcornelissen** [comment]
This should be fixed with the release of [v2.2.0](https://github.com/ericcornelissen/pinned-tabs-for-atom/releases/tag/v2.2.0) (minor release because it also includes 60df132678c9a8d084594f2efe5954fd4d3fb43e) Let me know if your issues persists or if you find yet another problem! :smile:

**Comment by HintonR** [comment]
Just updated. Looks good :)
