### ISSUE TITLE
Close all tabs but pinned

### ISSUE THREAD

**Issue by jerone** [ericcornelissen/pinned-tabs-for-atom#9]
Can I propose a feature for an command to close all tabs but pinned. Adding it to the contextmenu on the tabs would be great (when at least one tab is pinned).

**Comment by ericcornelissen** [comment]
I like this idea, I will try to get it to work as soon as possible :smile:

**Comment by ericcornelissen** [comment]
I implemented this into the package. I did not publish it to APM yet because I want to fix #10 first. If you want, you can test its functionality by cloning this repository.

Also, the entry for this feature in the context menu is now at kind of a wierd place (it is now second in the list). I would prefer to move it 'Close tabs to the right'. Unfortunately I couldn't get this to work, do you by any chance know how to do this?

**Comment by jerone** [comment]
> Also, the entry for this feature in the context menu is now at kind of a wierd place (it is now second in the list). I would prefer to move it 'Close tabs to the right'. Unfortunately I couldn't get this to work, do you by any chance know how to do this?

Have a read here: https://github.com/atom/atom/issues/6270

**Comment by ericcornelissen** [comment]
Well, that seems clear to me :cry:
